theme: jekyll-theme-cayman
title: "Workshop on Conversational Search for Complex Information Needs"
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Workshop on Conversational Search for Complex Information Needs
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
# url: "https://convsearch-complex-info-needs.github.io"

github_username: convsearch-complex-info-needs
